### ISSUE TITLE
is.number(NaN) returning true

### ISSUE THREAD

**Issue by eriklharper** [arasatasaygin/is.js#104] opened 2015-03-26 23:02 UTC
Not sure why, but that is what is happening: 

![image](https://cloud.githubusercontent.com/assets/821864/6858999/7074f382-d3d1-11e4-8703-8bbfe5b681ad.png)

Running 0.4.0 of is_js

**Comment by didxga** [comment] 2015-03-27 05:23
Hi @eriklharper, I think this has been fixed. Please check the latest version.

**Comment by fslone** [comment] 2015-03-27 13:22
@didxga I verified that it isn't fixed in 0.4.0. The problem is that when you pass this in:

```
is.number(NaN)
```

The method converts the value to a string and checks whether it's part of the number object:

```
// is a given value number?
is.number = function(value) {
    return toString.call(value) === '[object Number]';
};
```

Because NaN is a property of the Number object, NaN is returning true. The solution would be to make the test more robust to prevent this:

```
// is a given value number?
is.number = function(value) {
    return !isNaN(value) && typeof(value) !== "string";
};
```

**Comment by jonhester** [comment] 2015-03-27 14:12
https://github.com/arasatasaygin/is.js/issues/72 I actually fixed this last month.
```
console.log(typeof NaN) 
// number
```
It was decided that even though javascript considers NaN a number still it goes against the point of the check so it now returns false for NaN.

**Comment by ekaradon** [comment] 2015-07-10 08:36
Could you please also change then the return of is.nan?
Today, is.nan(null) return false, which means that null is considered as a number by the language. It is because javascript evaluated everything false as "0". 
So you will always have values considered as number through NaN() when it is null, false or empty string.
I think the library is should remove this inconsistency from the language.

**Comment by ironmaniiith** [comment] 2016-01-02 15:44
If NaN returns false, that does not mean that it has to be a number.
NaN in javascript is a predefined keyword, which is neither equal to null, nor undefined and not even itself (yes..!!). But still, it is a number.
Hence it is correct if is.nan returns false for null.

```javascript
console.log(NaN == NaN)
// false
```

Also NaN will "only" return true when the argument passed is not equal to itself (to keep it simple, when NaN is passed as argument).
Hope that helps. :-)

**Comment by ironmaniiith** [comment] 2016-01-02 15:47
@ekaradon 

If is.nan returns false on something, that does not mean that it has to be a number.
NaN in javascript is a predefined keyword, which is neither equal to null, nor undefined and not even itself (yes..!!). But still, it is a number.
Hence it is correct if is.nan returns false for null.

```javascript
console.log(NaN == NaN)
// false
```

Also is.nan will "only" return true when the argument passed is not equal to itself (to keep it simple, when NaN is passed as argument).
Hope that helps. :-)

**Closed** 2016-06-23 21:57 UTC
Labels: invalid
