### ISSUE TITLE
Ubuntu not being recognized as Linux

### ISSUE THREAD

**Issue by inad9300** [arasatasaygin/is.js#131] opened 2015-05-16 14:08 UTC
Hi,

I think the OS needs some more checks to be determined accurately. In this particular case I've found that Ubuntu is not recognized as a GNU/Linux OS. The `navigator.appVersion` value is `"5.0 (X11)"`. Typical scripts that perform this task include a forth check to determine if the OS is Unix-like. You can see an example here: http://www.javascripter.net/faq/operatin.htm

**Comment by ironmaniiith** [comment] 2016-06-25 01:09
@inad9300 , can you please tell which browser and version of ubuntu are you using..?

**Comment by inad9300** [comment] 2016-06-29 11:58
It was quite a long ago, but it was most likely Chromium.

**Comment by ironmaniiith** [comment] 2018-05-21 07:33
Unable to reproduce, closing this issue for now.

**Closed by ironmaniiith** 2018-05-21 07:33 UTC
Labels: bug
